### PR TITLE
Api collections

### LINKED ISSUE #1664: API Create/Update collection routes are not working
## Bug Description

The create and update collection routes through the ETEngine API seem to not work. The other routes, index, show and even destroy work.

---

### Steps to Reproduce

1. Run MyETM and ETEngine locally.
2. Make a create or update call according to the API documentation, like the
     following curl (just make sure the scenario_ids are correct in your case):
 ```
 curl -X POST "http://localhost:3000/api/v3/collections" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $ETM_API_TOKEN" \
  -d '{"title":"New collection name", "scenario_ids":[47]}'
 ```
 4. We just get the response:`{"errors":["Not found"]}`
---

## Expected interaction

Those routes are a kind of pass-thru so they should work very similarly to their equivalent routes in the MyETM API.

---

### Proposed solutions

In my investigation the issue seems to originate in the authorization process for update.
create routes in Api::V3:CollectionController:
```
      before_action(only: %i[create update]) do
        authorize!(:write, Scenario)
      end
```

### PR DESCRIPTION
**Pull request by aaccensi**
## Description

The create and update collections via the API has been fixed by bringing it closer in concept to a simple pass-thru towards MyETM. Yet a couple of actions are still happening on ETEngine to make the API more friendly:
- We do not need to use the `version` parameter, it can be used but otherwise it is simply defaulted from the settings.
- In the very same manner, the `interpolation` parameter can be used but otherwise it is simply defaulted to false.

## Type of change

- [x] Bug fix
- [ ] New feature
- [x] Enhancement
- [ ] Documentation

## Checklist

- [x] I have tested these changes
- [x] I have updated documentation as needed
- [x] I have tagged the relevant people for review

## Related Issues

Closes #1664

### CODE REVIEW

File: app/controllers/api/v3/collections_controller.rb [hunk 1]
```diff
@@ -39,8 +39,7 @@ def create
           endpoint_path: '/api/v1/collections',
           method: :post
         ).call(
-          params: params.permit!.to_h.merge(version: Settings.version_tag),
-          ability: current_ability,
+          params: collection_params({ version: Settings.version_tag, interpolation: false }),
```
Comment (noracato) [inline app/controllers/api/v3/collections_controller.rb]: Double check `interpolation: false`

File: app/services/upsert_transition_path.rb [hunk 2]
```diff
@@ -21,51 +21,19 @@ def initialize(endpoint_path:, method:)
...
-    accessible_ids = scenarios.map(&:id)
-
-    if accessible_ids == ids.sort
-      Success(accessible_ids)
-    else
-      missing_ids = ids - accessible_ids
-      Failure(scenario_ids: missing_ids.index_with { |_id| ['does not exist'] })
-    end
-  end
-
```
Comment (noracato) [inline app/services/upsert_transition_path.rb]: Keep for backwards compatibility

File: app/services/upsert_transition_path.rb [hunk 3]
```diff
@@ -21,51 +21,19 @@ def initialize(endpoint_path:, method:)
...
   end
-
-  # # Decorates the params with the scenario's area code and end year when a scenario_id is set.
-  def full_params(params, scenarios)
-    return params if scenarios.blank?
-
-    # The highest end year is always the last scenario.
-    latest_scenario = scenarios.last
-    params.merge(area_code: latest_scenario.area_code, end_year: latest_scenario.end_year)
-  end
```
Comment (noracato) [inline app/services/upsert_transition_path.rb]: Yes, but merge with `version` instead?
