### PR TITLE
Rescaling curves

### LINKED ISSUE #1514: Don't normalise load/capacity profiles when downloading
At the moment, capacity profiles (load profiles) are normalised when you download them from a scenario. This is inconvenient because if you want to re-use that profile in another scenario (for example), it will not work the same way.

### PR DESCRIPTION
**Pull request by louispt1**
This PR builds upon [the other curve PR](https://github.com/quintel/etengine/pull/1563) to enable downloading capacity profiles as they were uploaded (rescaled based on their full load hours).

If you're happy with it @kndehaan, then please also tag @noracato as a reviewer for a check of the code!

Closes #1514

### CODE REVIEW

**Comment by kndehaan** [comment]
Nice work! Downloading the capacity profiles in the same format as uploaded works well through the front-end. Curious when this [issue](https://github.com/quintel/etengine/pull/1563#pullrequestreview-2799500373) is fixed, the same result is obtained when retrieving custom curves via the API.

**Review by kndehaan — COMMENTED** [review]
Seems to work well via the API via scenario-tools (incl [this fix](https://github.com/quintel/scenario-tools/pull/46)) as well!

**Review by kndehaan — APPROVED** [review]

File: app/controllers/api/v3/custom_curves_controller.rb [hunk 1]
```diff
@@ -46,16 +46,29 @@ def index
...
+        # Only pull FLH & rescale for CapacityProfile curves
+        if config.processor_key == :capacity_profile
+          flh_key     = config.input_keys.first
+          full_load   = user_curve.scenario.user_values[flh_key]
+          scaled_curve = CurveHandler::Reducers::Rescaler
+                           .new(raw_curve, full_load)
+                           .call
+        else
+          scaled_curve = raw_curve
+        end
```
Comment (noracato) [inline app/controllers/api/v3/custom_curves_controller.rb:62]: This logic is too complicated for a controller. Remember that we want methods to generally be smaller than 10 lines.

**Comment by kndehaan** [comment]
Before merging, check:

- [ ] Descriptions ETModel
- [ ] Documentation
- [ ] What's new / changelog

**Comment by kndehaan** [comment]
Updated front-end descriptions and documentation in:
- https://github.com/quintel/documentation/pull/230
- https://github.com/quintel/etmodel/pull/4494

**Comment by kndehaan** [comment]
I tested the functionality again, but something goes wrong. I uploaded two different flat curves for wind on land with 0.5 and 0.9 for each hour, but when downloading the curves again, I get a flat curve with `0.399543378995433` for each hour back. @louispt1

**Comment by louispt1** [comment]
@kndehaan do you mind testing it again? I think I have resolved the flh issue now (I also rebased the branch).

**Comment by kndehaan** [comment]
@louispt1 the uploading / downloading curve in same format goes well now, and the curve is processed correctly in the model in calculating hourly flows. However, the 'registered' full load hours are incorrect, depicted in the front-end or via the engine:
image

image

The value registered there is still bound by the min and max value of the regular FLH slider.

File: app/serializers/custom_profile_curve_serializer.rb [hunk 2]
```diff
@@ -6,11 +6,21 @@ class CustomProfileCurveSerializer < CustomCurveSerializer
...
   end
+
+  # Internal: If the config has a reducer, we know it's a capacity profile
+  # many of them have already been normalized at this point, so we
+  # have to check the flh input they set
+  #
+  # Returns the full load hours associated to the profile
+  def reduced
+    if config.sets_inputs? && @user_curve.scenario.user_values.key?(config.input_keys.first)
+      @user_curve.scenario.user_values[config.input_keys.first]
```
Comment (kndehaan) [inline app/serializers/custom_profile_curve_serializer.rb:21]: `first` should probably be replaced here as well by `last` in at least line 21 (and also line 20?) to show the correct flhs in the front-end and engine

Comment (louispt1) [reply app/serializers/custom_profile_curve_serializer.rb]: I think you're right - I made the changes now. Let me know if it's still not working and we can have a look together!

**Comment by kndehaan** [comment]
Checklist for testing:
- Front-end
    - [ ] Correct processing of capacity_curve
    - [ ] Download in the same format
    - [ ] Correct depicted full_load_hours (ignore mix/max value regular slider)
    - [ ] Verify other curve types not affected
- Engine
    - [ ] Correct FLH for user_curve input
    - [ ] Correct FLH depicted in engine API custom curve view
- API
    - [ ] Download of capacity profile curve in correct format
    - [ ] Upload of capacity profile works as expected

**Comment by kndehaan** [comment]
Thanks @louispt1, everything seems to work well now! I'll check in with @mabijkerk regarding the PRs for updated slide description and documentation.

**Review by noracato — APPROVED** [review]
LGTM! Nice work!
